name: Cypress CI
on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Instalar pnpm
        uses: pnpm/action-setup@v4

      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24'
          cache: 'pnpm'

      - name: Instalar dependências
        run: pnpm install

      - name: Executar testes E2E
        uses: cypress-io/github-action@v6
        with:
          install: false